/* ══ DNSCOPE — Export ════════════════════════════════════════════════════ */

function doExport() {
  const fmt = document.querySelector('input[name="exp-fmt"]:checked')?.value || 'json';
  const state = getScanState();
  if (!state) { showToast('No scan data to export', 'error'); return; }

  if (fmt === 'json') exportJSON(state);
  if (fmt === 'md') exportMarkdown(state);

  document.getElementById('export-modal').classList.remove('open');
}

function exportJSON(state) {
  const out = {
    target: state.target,
    targetType: state.targetType,
    scannedAt: state.scannedAt,
    ips: state.ips,
    asn: state.asn,
    ipInfo: state.ipInfo,
    cloud: state.cloud,
    cdnwaf: state.cdnwaf,
    passiveDNS: state.pdns,
    certificates: state.certs,
    subdomains: Object.fromEntries(
      Object.entries(state.subdomains).map(([k, v]) => [k, [...v]])
    ),
    cohosted: state.cohosted,
  };
  download(`dnscope-${state.target}-${ts()}.json`, JSON.stringify(out, null, 2), 'application/json');
}

function exportMarkdown(state) {
  const a = state.asn;
  const ip = state.ipInfo;
  const lines = [
    `# DNSCOPE — ${state.target}`,
    ``,
    `**Type:** ${state.targetType} · **Scanned:** ${state.scannedAt}`,
    ``,
    `## Overview`,
    `- **IPs:** ${(state.ips || []).join(', ') || '—'}`,
    `- **Organization:** ${a?.description || ip?.orgName || '—'}`,
    `- **ASN:** AS${a?.asn || '—'} · **Country:** ${a?.country || ip?.country || '—'}`,
    `- **Prefix:** ${a?.prefix || '—'}`,
    ``,
    `## Cloud / Hosting`,
    `- **Provider:** ${state.cloud?.name || 'Unknown'}`,
    `- **Confidence:** ${state.cloud?.confidence || '—'}`,
    ``,
    `## CDN / WAF`,
    ...(state.cdnwaf?.length
      ? state.cdnwaf.map(c => `- **${c.name}** (${c.type})${c.evidence?.length ? ' — ' + c.evidence.join(', ') : ''}`)
      : ['- None detected']),
    ``,
    `## Passive DNS (${state.pdns.length} records)`,
    `| Name | Type | Value | First | Last | Source |`,
    `|------|------|-------|-------|------|--------|`,
    ...state.pdns.slice(0, 100).map(r =>
      `| ${r.name} | ${r.type} | ${r.value} | ${r.first || r.date || '—'} | ${r.last || '—'} | ${r.source} |`
    ),
    ``,
    `## Certificates (${state.certs.length})`,
    `| CN | SANs | Issuer | Valid From | Valid To | Source |`,
    `|----|------|--------|------------|----------|--------|`,
    ...state.certs.map(c =>
      `| ${c.cn} | ${c.sans.length} | ${c.issuer} | ${c.notBefore || '—'} | ${c.notAfter || '—'} | ${c.source} |`
    ),
    ``,
    `## Subdomains (${Object.keys(state.subdomains).length})`,
    ...Object.entries(state.subdomains).map(([s, srcs]) => `- ${s} [${[...srcs].join(', ')}]`),
    ``,
    `## Co-hosted (${state.cohosted.length})`,
    ...state.cohosted.map(c => `- ${c.domain} (${c.ip}) [${c.source}]`),
    ``,
    `---`,
    `Generated by [DNSCOPE](https://h3ad-sec.github.io/DNSCOPE/) · H3AD-SEC`,
  ];
  download(`dnscope-${state.target}-${ts()}.md`, lines.join('\n'), 'text/markdown');
}

function download(filename, content, type) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

function ts() {
  return new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
}
