/* ══ DNSCOPE — Export ════════════════════════════════════════════════════ */

function doExport() {
  const fmt = document.querySelector('input[name="exp-fmt"]:checked')?.value || 'json';
  const state = getScanState();
  if (!state) { showToast('No scan data to export', 'error'); return; }

  if (fmt === 'json') exportJSON(state);
  if (fmt === 'md') exportMarkdown(state);
  if (fmt === 'stix') exportSTIX(state);
  if (fmt === 'misp') exportMISP(state);
  if (fmt === 'print') { document.getElementById('export-modal').classList.remove('open'); setTimeout(() => window.print(), 200); return; }

  document.getElementById('export-modal').classList.remove('open');
}

function exportJSON(state) {
  const out = {
    target: state.target,
    targetType: state.targetType,
    scannedAt: state.scannedAt,
    ips: state.ips,
    asn: state.asn,
    ipInfo: state.ipInfo,
    cloud: state.cloud,
    cdnwaf: state.cdnwaf,
    whois: state.whois,
    threatIntelligence: state.ti,
    liveDNS: state.liveDNS,
    passiveDNS: state.pdns,
    certificates: state.certs,
    subdomains: Object.fromEntries(
      Object.entries(state.subdomains).map(([k, v]) => [k, [...v]])
    ),
    cohosted: state.cohosted,
    ports: state.ports,
    fingerprints: state.fingerprints,
    urlscan: state.urlscan,
  };
  download(`dnscope-${state.target}-${ts()}.json`, JSON.stringify(out, null, 2), 'application/json');
}

function exportMarkdown(state) {
  const a = state.asn;
  const ip = state.ipInfo;
  const w = state.whois;
  const ti = state.ti;
  const lines = [
    `# DNSCOPE — ${state.target}`,
    ``,
    `**Type:** ${state.targetType} · **Scanned:** ${state.scannedAt}`,
    ``,
    `## Overview`,
    `- **IPs:** ${(state.ips || []).join(', ') || '—'}`,
    `- **Organization:** ${a?.description || ip?.orgName || '—'}`,
    `- **ASN:** AS${a?.asn || '—'} · **Country:** ${a?.country || ip?.country || '—'}`,
    `- **Prefix:** ${a?.prefix || '—'}`,
    ``,
    `## WHOIS`,
    `- **Registrar:** ${w?.registrar || '—'}`,
    `- **Created:** ${w?.created?.split('T')[0] || '—'}`,
    `- **Expires:** ${w?.expiry?.split('T')[0] || '—'}`,
    `- **NRD:** ${w?.isNRD ? `YES (${w.daysSince} days old)` : 'No'}`,
    ``,
    `## Threat Intelligence`,
    `- **VT Detections:** ${ti?.vt?.malicious || 0}/${ti?.vt?.total || 0}`,
    `- **OTX Pulses:** ${ti?.otx?.pulseCount || 0}`,
    `- **ThreatFox IOCs:** ${ti?.threatfox?.iocs?.length || 0}`,
    ``,
    `## Cloud / Hosting`,
    `- **Provider:** ${state.cloud?.name || 'Unknown'}`,
    `- **Confidence:** ${state.cloud?.confidence || '—'}`,
    ``,
    `## CDN / WAF`,
    ...(state.cdnwaf?.length
      ? state.cdnwaf.map(c => `- **${c.name}** (${c.type})${c.evidence?.length ? ' — ' + c.evidence.join(', ') : ''}`)
      : ['- None detected']),
    ``,
    `## Fingerprints`,
    `- **JARM:** ${state.fingerprints?.jarm || '—'}`,
    `- **Favicon Hash:** ${state.fingerprints?.faviconHash ?? '—'}`,
    ``,
    `## Passive DNS (${state.pdns.length} records)`,
    `| Name | Type | Value | First | Last | Source |`,
    `|------|------|-------|-------|------|--------|`,
    ...state.pdns.slice(0, 100).map(r =>
      `| ${r.name} | ${r.type} | ${r.value} | ${r.first || r.date || '—'} | ${r.last || '—'} | ${r.source} |`
    ),
    ``,
    `## Certificates (${state.certs.length})`,
    `| CN | SANs | Issuer | Valid From | Valid To | Source |`,
    `|----|------|--------|------------|----------|--------|`,
    ...state.certs.map(c =>
      `| ${c.cn} | ${c.sans.length} | ${c.issuer} | ${c.notBefore || '—'} | ${c.notAfter || '—'} | ${c.source} |`
    ),
    ``,
    `## Subdomains (${Object.keys(state.subdomains).length})`,
    ...Object.entries(state.subdomains).map(([s, srcs]) => `- ${s} [${[...srcs].join(', ')}]`),
    ``,
    `## Co-hosted (${state.cohosted.length})`,
    ...state.cohosted.map(c => `- ${c.domain} (${c.ip}) [${c.source}]`),
    ``,
    `---`,
    `Generated by [DNSCOPE](https://h3ad-sec.github.io/DNSCOPE/) · H3AD-SEC`,
  ];
  download(`dnscope-${state.target}-${ts()}.md`, lines.join('\n'), 'text/markdown');
}

function exportSTIX(state) {
  const uid = () => {
    if (typeof crypto !== 'undefined' && crypto.randomUUID) return crypto.randomUUID();
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
      const r = Math.random() * 16 | 0;
      return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
    });
  };

  const objects = [];

  if (state.targetType === 'domain') {
    objects.push({ type: 'domain-name', spec_version: '2.1', id: `domain-name--${uid()}`, value: state.target });
  } else {
    objects.push({ type: 'ipv4-addr', spec_version: '2.1', id: `ipv4-addr--${uid()}`, value: state.target });
  }

  state.ips.filter(isIP).forEach(ip => {
    objects.push({ type: 'ipv4-addr', spec_version: '2.1', id: `ipv4-addr--${uid()}`, value: ip });
  });

  Object.keys(state.subdomains).forEach(sub => {
    objects.push({ type: 'domain-name', spec_version: '2.1', id: `domain-name--${uid()}`, value: sub });
  });

  state.cohosted.forEach(h => {
    objects.push({ type: 'domain-name', spec_version: '2.1', id: `domain-name--${uid()}`, value: h.domain });
  });

  if (state.asn?.asn) {
    objects.push({
      type: 'autonomous-system', spec_version: '2.1',
      id: `autonomous-system--${uid()}`,
      number: state.asn.asn,
      name: state.asn.description || '',
    });
  }

  if (state.fingerprints?.jarm) {
    objects.push({
      type: 'network-traffic', spec_version: '2.1',
      id: `network-traffic--${uid()}`,
      extensions: { 'tls-ext': { ja3_hash: { md5: state.fingerprints.jarm } } },
    });
  }

  const bundle = { type: 'bundle', id: `bundle--${uid()}`, objects };
  download(`dnscope-${state.target}-${ts()}.stix.json`, JSON.stringify(bundle, null, 2), 'application/json');
}

function exportMISP(state) {
  const attr = (type, cat, value, comment) => ({
    type, category: cat, value, comment: comment || '', to_ids: true,
  });
  const attrs = [];

  if (state.targetType === 'domain') {
    attrs.push(attr('domain', 'Network activity', state.target, 'Scanned target'));
  } else {
    attrs.push(attr('ip-dst', 'Network activity', state.target, 'Scanned target'));
  }

  state.ips.filter(isIP).forEach(ip =>
    attrs.push(attr('ip-dst', 'Network activity', ip, 'Resolved IP'))
  );

  Object.keys(state.subdomains).forEach(sub =>
    attrs.push(attr('domain', 'Network activity', sub, 'Subdomain'))
  );

  state.pdns.filter(r => isIP(r.value)).forEach(r =>
    attrs.push(attr('ip-dst', 'Network activity', r.value, `Passive DNS · ${r.source}`))
  );

  if (state.fingerprints?.jarm)
    attrs.push(attr('other', 'Network activity', state.fingerprints.jarm, 'JARM fingerprint'));
  if (state.fingerprints?.faviconHash !== null && state.fingerprints?.faviconHash !== undefined)
    attrs.push(attr('other', 'Network activity', String(state.fingerprints.faviconHash), 'Favicon hash (Shodan)'));

  if (state.asn?.asn)
    attrs.push(attr('AS', 'Network activity', 'AS' + state.asn.asn, state.asn.description || ''));

  const event = {
    Event: {
      info: `DNSCOPE: ${state.target}`,
      date: state.scannedAt ? state.scannedAt.split('T')[0] : new Date().toISOString().split('T')[0],
      threat_level_id: '2',
      analysis: '2',
      distribution: '0',
      Attribute: attrs,
    },
  };
  download(`dnscope-${state.target}-${ts()}.misp.json`, JSON.stringify(event, null, 2), 'application/json');
}

function download(filename, content, type) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

function ts() {
  return new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
}
